[package]
name = "adventofcode-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
advent_tools = {path = "./advent_tools"}
tokio = { version = "1", features = ["full"] }
regex = "1.11.1"
itertools = "0.11"
rayon = "1.7"
trie-rs = "0.4.2"

